/* tslint:disable */
/* eslint-disable */
/**
 * Todo example
 * The Todo API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TodoEntity } from './todo-entity';

/**
 *
 * @export
 * @interface GetTodoListResponse
 */
export interface GetTodoListResponse {
  /**
   *
   * @type {Array<TodoEntity>}
   * @memberof GetTodoListResponse
   */
  todoes: Array<TodoEntity>;
}
