/* tslint:disable */
/* eslint-disable */
/**
 * Todo example
 * The Todo API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TodoEntity
 */
export interface TodoEntity {
  /**
   *
   * @type {string}
   * @memberof TodoEntity
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TodoEntity
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof TodoEntity
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof TodoEntity
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof TodoEntity
   */
  updatedAt: string;
}
